CREATE TABLE NOBEL(
YEAR INTEGER,
SUBJECT TEXT,
WINNER TEXT,
COUNTRY TEXT,
CATEGORY TEXT
);

INSERT INTO NOBEL(YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY) VALUES
(2025, 'LITERATURE', 'LÁSZLÓ KRASZNAHORKAI', 'HUNGARY', 'WRITER'),
(2024, 'LITERATURE', 'HAN KANG', 'SOUTH KOREA', 'WRITER'),
(2023, 'PHYSICS', 'PIERRE AGOSTINI', 'FRANCE', 'SCIENTIST'),
(2022, 'MEDICINE', 'SVANTE PÄÄBO', 'SWEDEN', 'SCIENTIST'),
(2021, 'PEACE', 'MARIA RESSA', 'PHILIPPINES', 'ACTIVIST'),
(2020, 'LITERATURE', 'LOUISE GLÜCK', 'USA', 'WRITER'),
(2019, 'PHYSICS', 'JAMES PEEBLES', 'USA', 'SCIENTIST');

SELECT * FROM NOBEL ORDER BY YEAR DESC;
SELECT * FROM NOBEL WHERE SUBJECT NOT LIKE "P%" ORDER BY YEAR ,WINNER DESC;