CREATE TABLE NOBEL_WIN (
YEAR INTEGER,
SUBJECT TEXT,
WINNER TEXT,
COUNTRY TEXT,
CATEGORY TEXT
);

INSERT INTO NOBEL_WIN (YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY) VALUES
(1978, 'PHYSICS', 'HANNES ALFVEN', 'SWEDEN', 'SCIENTIST'),
(1978, 'PHYSICS', 'LOUIS NEEL', 'FRANCE', 'SCIENTIST'),
(1971, 'PHYSICS', 'PAUL', 'FRANCE', 'SCIENTIST'),
(1971, 'CHEMISTRY', 'HAMILTON', 'SWEDEN', 'LINGUIST'),
(1972, 'LITERATURE', 'BERNARD KELSON', 'GERMANY', 'ECONOMIST');

SELECT * from NOBEL_WIN

SELECT * FROM NOBEL_WIN WHERE SUBJECT NOT LIKE "P%" ORDER BY YEAR ,WINNER DESC;

SELECT * FROM NOBEL_WIN WHERE SUBJECT LIKE "P%" ORDER BY YEAR ,WINNER DESC;
